[tool.bumpversion]
current_version = "0.2.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "cargo.toml"

[[tool.bumpversion.files]]
filename = "cargo.lock"

[[tool.bumpversion.files]]
filename = "Makefile"

[[tool.bumpversion.files]]
filename = "package.json"

[[tool.bumpversion.files]]
filename = "package-lock.json"
search = "\"name\": \"tree-sitter-cylc\",\n  \"version\": \"{current_version}\""
replace = "\"name\": \"tree-sitter-cylc\",\n  \"version\": \"{new_version}\""

[[tool.bumpversion.files]]
filename = "package-lock.json"
search = "\"name\": \"tree-sitter-cylc\",\n      \"version\": \"{current_version}\""
replace = "\"name\": \"tree-sitter-cylc\",\n      \"version\": \"{new_version}\""
